name: Hello Workflow

on:

  workflow_dispatch:

    inputs:  

      hidden_value:

        type: string

        required: true

        description: value to be hidden

 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Print Hello

        run: |

          HIDDEN_VALUE=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.hidden_value')

          echo "::add-mask::$HIDDEN_VALUE"

          echo "$HIDDEN_VALUE"
